const Joi = require('joi');

module.exports.articleSchema = Joi.object({
    article: Joi.object({
        title: Joi.string().required(),
        game: Joi.string().required(),
        release: Joi.string().required(),
        console: Joi.string().required(),
        //images: Joi.string().required(),
        blog: Joi.string().required(),
        movieOne: Joi.string().required(),
        movieOneImage: Joi.string().required(),
        movieTwo: Joi.string().required(),
        movieTwoImage: Joi.string().required(),
        movieThree: Joi.string().required(),
        movieThreeImage: Joi.string().required(),
        movieFour: Joi.string().required(),
        movieFourImage: Joi.string().required(),
        movieFive: Joi.string().required(),
        movieFiveImage: Joi.string().required(),
        musicOne: Joi.string().required(),
        musicOneImage: Joi.string().required(),
        musicTwo: Joi.string().required(),
        musicTwoImage: Joi.string().required(),
        musicThree: Joi.string().required(),
        musicThreeImage: Joi.string().required(),
        musicFour: Joi.string().required(),
        musicFourImage: Joi.string().required(),
        musicFive: Joi.string().required(),
        musicFiveImage: Joi.string().required(),
        nbaOne: Joi.string().required(),
        nbaOneImage: Joi.string().required(),
        nbaTwo: Joi.string().required(),
        nbaTwoImage: Joi.string().required(),
        nbaThree: Joi.string().required(),
        nbaThreeImage: Joi.string().required(),
        nbaFour: Joi.string().required(),
        nbaFourImage: Joi.string().required(),
        nbaFive: Joi.string().required(),
        nbaFiveImage: Joi.string().required(),
        nhlOne: Joi.string().required(),
        nhlOneImage: Joi.string().required(),
        nhlTwo: Joi.string().required(),
        nhlTwoImage: Joi.string().required(),
        nhlThree: Joi.string().required(),
        nhlThreeImage: Joi.string().required(),
        nhlFour: Joi.string().required(),
        nhlFourImage: Joi.string().required(),
        nhlFive: Joi.string().required(),
        nhlFiveImage: Joi.string().required(),
        mlbOne: Joi.string().required(),
        mlbOneImage: Joi.string().required(),
        mlbTwo: Joi.string().required(),
        mlbTwoImage: Joi.string().required(),
        mlbThree: Joi.string().required(),
        mlbThreeImage: Joi.string().required(),
        mlbFour: Joi.string().required(),
        mlbFourImage: Joi.string().required(),
        mlbFive: Joi.string().required(),
        mlbFiveImage: Joi.string().required(),
        nflOne: Joi.string().required(),
        nflOneImage: Joi.string().required(),
        nflTwo: Joi.string().required(),
        nflTwoImage: Joi.string().required(),
        nflThree: Joi.string().required(),
        nflThreeImage: Joi.string().required(),
        nflFour: Joi.string().required(),
        nflFourImage: Joi.string().required(),
        nflFive: Joi.string().required(),
        nflFiveImage: Joi.string().required(),
    }).required()
});

module.exports.reviewSchema = Joi.object({
    review: Joi.object({
        rating: Joi.number().required().min(1).max(10),
        body: Joi.string().required()
    }).required()
});

